CREATE DATABASE IF NOT EXISTS mausam_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE mausam_db;

CREATE TABLE users (
    user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    daily_routine VARCHAR(30) NOT NULL,
    outdoor_time VARCHAR(20) NOT NULL,
    weather_interests JSON NOT NULL,
    weather_use VARCHAR(30) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    CONSTRAINT users_name_not_blank
        CHECK (length(trim(name)) > 0),
    CONSTRAINT users_weather_interests_is_array
        CHECK (JSON_TYPE(weather_interests) = 'ARRAY'),
    CONSTRAINT users_weather_interests_limit
        CHECK (JSON_LENGTH(weather_interests) BETWEEN 1 AND 3)
);

CREATE TABLE login_data (
    login_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL UNIQUE,
    email VARCHAR(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    CONSTRAINT login_data_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT login_data_email_format
        CHECK (email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'),
    CONSTRAINT login_data_bcrypt_hash
        CHECK (password_hash REGEXP '^\\$2[aby]\\$[0-9]{2}\\$')
);

CREATE TABLE auth_sessions (
    session_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    CONSTRAINT auth_sessions_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_users_created_at ON users(created_at);
CREATE INDEX idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX idx_auth_sessions_expires_at ON auth_sessions(expires_at);

-- Example queries. The password_hash value must be generated by bcrypt in the backend.
INSERT INTO users (
    name, daily_routine, outdoor_time, weather_interests, weather_use
) VALUES (
    'Aarav', 'active', 'morning',
    JSON_ARRAY('temperature', 'rain', 'uv'), 'exercise'
);

-- Use the AUTO_INCREMENT value from the preceding INSERT.
SET @sample_user_id = LAST_INSERT_ID();

INSERT INTO login_data (user_id, email, password_hash)
VALUES (@sample_user_id, 'aarav@example.com', '$2b$12$BACKEND_GENERATED_BCRYPT_HASH_GOES_HERE');

SELECT
    u.user_id, u.name, l.email, u.daily_routine, u.outdoor_time,
    u.weather_interests, u.weather_use, u.created_at, u.updated_at
FROM users AS u
JOIN login_data AS l ON l.user_id = u.user_id
WHERE l.email = 'aarav@example.com';

UPDATE users
SET daily_routine = 'work',
    outdoor_time = 'evening',
    weather_interests = JSON_ARRAY('rain', 'alerts', 'wind'),
    weather_use = 'commute',
    updated_at = CURRENT_TIMESTAMP(3)
WHERE user_id = @sample_user_id;

DELETE FROM users WHERE user_id = @sample_user_id;
